--- Query 1 : List all employees along with their department names
SELECT E.EMP_ID, E.F_NAME, E.L_NAME, D.DEP_NAME 
FROM EMPLOYEES E JOIN DEPARTMENTS D 
ON E.DEP_ID = D.DEPT_ID_DEP;


--- Query 2 : Find employees earning more than average salary
SELECT EMP_ID, F_NAME, L_NAME, SALARY FROM EMPLOYEES 
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES);


--- Query 3 : List 10 top highest paid employees
SELECT F_NAME, L_NAME, SALARY FROM EMPLOYEES
ORDER BY SALARY DESC
LIMIT 10;


--- Query 4 : Count employees in each department
SELECT D.DEP_NAME, COUNT(E.EMP_ID) AS EMPLOYEE_COUNT
FROM EMPLOYEES E LEFT JOIN DEPARTMENTS D
ON E.DEP_ID = D.DEPT_ID_DEP
GROUP BY D.DEP_NAME;


--- Query 5 : List employees hired after a specific date
SELECT E.F_NAME, E.L_NAME, JH.START_DATE 
FROM EMPLOYEES E JOIN JOB_HISTORY JH
ON E.EMP_ID = JH.EMPL_ID;


--- Query 6 : Find departments with more than 3 employees
SELECT D.DEP_NAME, COUNT(E.EMP_ID) AS EMPLOYEE_COUNT
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON E.DEP_ID = D.DEPT_ID_DEP
GROUP BY D.DEP_NAME
HAVING COUNT(E.EMP_ID) > 2;


--- Query 7 : Find the total salary paid for each job role
SELECT J.JOB_TITLE, SUM(E.SALARY) AS TOTAL_SALARY
FROM EMPLOYEES E LEFT JOIN JOBS J
ON E.JOB_ID = J.JOB_IDENT
GROUP BY J.JOB_TITLE;


--- Query 8 : Calculate average salary for each department
SELECT D.DEP_NAME, ROUND(AVG(E.SALARY),2) AS AVERAGE_SALARY
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON E.DEP_ID = D.DEPT_ID_DEP
GROUP BY D.DEP_NAME;


--- Query 9 : Identify the highest paid employee in each department
WITH HIGHPAY AS (
    SELECT DEP_ID, F_NAME, L_NAME, SALARY,
    DENSE_RANK() OVER (PARTITION BY DEP_ID ORDER BY SALARY DESC) AS SALARY_RANKING
    FROM EMPLOYEES
    )
SELECT DEP_ID, F_NAME, L_NAME, SALARY FROM HIGHPAY
WHERE SALARY_RANKING = 1;


--- Query 10 : List all employees with their job title and department name
SELECT E.F_NAME, E.L_NAME, J.JOB_TITLE, D.DEP_NAME
FROM EMPLOYEES E JOIN JOBS J
ON E.JOB_ID = J.JOB_IDENT
JOIN DEPARTMENTS D ON D.DEPT_ID_DEP = E.DEP_ID;


--- Query 11 : Find employees who have changed jobs atleast once
SELECT E.EMP_ID, E.F_NAME, E.L_NAME, COUNT(JH.START_DATE) AS JOB_CHANGE_COUNT
FROM EMPLOYEES E INNER JOIN JOB_HISTORY JH
ON E.EMP_ID = JH.EMPL_ID
GROUP BY E.EMP_ID, E.F_NAME, E.L_NAME
HAVING COUNT(JH.START_DATE) > 1;


--- Query 12 : Find departments where average salary is above company overall average
SELECT D.DEP_NAME, AVG(E.SALARY) AS DEPARTMENT_AVERAGE
FROM EMPLOYEES E JOIN DEPARTMENTS D 
ON E.DEP_ID = D.DEPT_ID_DEP
GROUP BY D.DEP_NAME
HAVING AVG(E.SALARY) > (SELECT AVG(SALARY) FROM EMPLOYEES);


--- Query 13 : Rank employees by salary within each department
WITH EMP_BY_SALARY AS (
    SELECT EMP_ID, SALARY, DEP_ID,
    RANK() OVER (ORDER BY SALARY DESC)
    FROM EMPLOYEES
)
SELECT * FROM EMP_BY_SALARY;


--- Query 14 : Create procedure to get all employees by department ID
DELIMITER //
CREATE PROCEDURE EMP (IN DEPT_ID INT)
BEGIN
    SELECT F_NAME, L_NAME, DEP_ID
    FROM EMPLOYEES
    WHERE DEP_ID = DEPT_ID;
END //
DELIMITER ;

CALL EMP(2);


--- Query 15 : Find the most recent job change for each employee
WITH RECENT_JOB AS (
    SELECT EMPL_ID, START_DATE,
    ROW_NUMBER() OVER (PARTITION BY EMPL_ID ORDER BY START_DATE DESC) AS JOB_CHANGE
    FROM JOB_HISTORY
)
SELECT E.F_NAME, E.L_NAME, E.EMP_ID, RJ.START_DATE FROM EMPLOYEES E
INNER JOIN RECENT_JOB RJ
ON E.EMP_ID = RJ.EMPL_ID;


--- Query 16 : Create procedure that returns total employee count
DELIMITER //
CREATE PROCEDURE EMP_COUNT(OUT TOTAL_COUNT INT)
BEGIN
	SELECT COUNT(*) INTO TOTAL_COUNT FROM EMPLOYEES;
END //
DELIMITER ;

CALL EMP_COUNT(@total);
SELECT @total;


--- Query 17 : Find employees earning more than their own departments average
SELECT E.EMP_ID, E.F_NAME, E.L_NAME, E.SALARY, D.DEP_NAME
FROM EMPLOYEES E JOIN DEPARTMENTS D 
ON E.DEP_ID = D.DEPT_ID_DEP
WHERE E.SALARY > (SELECT AVG(E1.SALARY) FROM EMPLOYEES E1 WHERE E1.DEP_ID = E.DEP_ID);


--- Query 18 : Create a view showing employee name, job title and department and salary
CREATE VIEW EMP_DETAILS AS 
SELECT E.F_NAME, E.L_NAME, E.SALARY, D.DEP_NAME, J.JOB_TITLE
FROM EMPLOYEES E JOIN DEPARTMENTS D 
ON E.DEP_ID = D.DEPT_ID_DEP 
JOIN JOBS J ON J.JOB_IDENT = E.JOB_ID;

SELECT * FROM EMP_DETAILS;


--- Query 19 : Find the second highest salary in the company
WITH SECOND_HIGHEST AS (
    SELECT F_NAME, L_NAME, SALARY,
    DENSE_RANK() OVER (ORDER BY SALARY DESC) AS SALARY_DETAILS
    FROM EMPLOYEES
)
SELECT * FROM SECOND_HIGHEST
WHERE SECOND_HIGHEST.SALARY_DETAILS = 2;


--- Query 20 : List departments with their employee count and average salary
WITH DETAILS AS (
    SELECT D.DEP_NAME, COUNT(E.EMP_ID) AS EMPLOYEE_COUNT,
    ROUND(AVG(E.SALARY), 2) AS AVERAGE_SALARY
    FROM EMPLOYEES E JOIN DEPARTMENTS D
    ON E.DEP_ID = D.DEPT_ID_DEP
    GROUP BY D.DEP_NAME
)
SELECT * FROM DETAILS;


--- Query 21 : Find employees who worked in more than one department
SELECT E.EMP_ID, E.F_NAME, E.L_NAME, COUNT(DISTINCT JH.DEPT_ID) AS DEPT_COUNT
FROM EMPLOYEES E JOIN JOB_HISTORY JH
ON E.EMP_ID = JH.EMPL_ID
GROUP BY E.EMP_ID, E.F_NAME, E.L_NAME
HAVING COUNT(DISTINCT JH.DEPT_ID) > 1;


--- Query 22 : Create a view of high earning employees above 10000 salary
CREATE VIEW HIGH_SALARY AS
SELECT F_NAME, L_NAME, SALARY 
FROM EMPLOYEES
WHERE SALARY > 10000;

SELECT * FROM HIGH_SALARY;


--- Query 23 : Create procedure that takes salary range and returns matching employees
DELIMITER //
CREATE PROCEDURE SALARY_RANGE(IN MIN_SALARY INT, IN MAX_SALARY INT)
BEGIN
	SELECT EMP_ID, F_NAME, L_NAME, SALARY
    FROM EMPLOYEES
    WHERE SALARY BETWEEN MIN_SALARY AND MAX_SALARY;
END //
DELIMITER ;

CALL SALARY_RANGE(45000, 100000);


--- Query 24 : Top 3 high paid employees per department
WITH TOP3 AS ( 
    SELECT EMP_ID, F_NAME, L_NAME, SALARY, DEP_ID,
    DENSE_RANK() OVER (PARTITION BY DEP_ID ORDER BY SALARY DESC) AS SALARY_RANK
    FROM EMPLOYEES
)
SELECT D.DEP_NAME, TP.F_NAME, TP.L_NAME, TP.SALARY, TP.SALARY_RANK
FROM TOP3 TP JOIN DEPARTMENTS D
ON TP.DEP_ID = D.DEPT_ID_DEP
WHERE TP.SALARY_RANK <= 3
ORDER BY D.DEP_NAME, TP.SALARY_RANK;


--- Query 25 : Complete employee career summary report
WITH CAREER_SUMMARY AS (
    SELECT E.EMP_ID, E.F_NAME, E.L_NAME, E.SALARY, D.DEP_NAME, J.JOB_TITLE,
    COUNT(JH.EMPL_ID) AS JOB_CHANGES,
    DENSE_RANK() OVER (ORDER BY E.SALARY DESC) AS SALARY_RANK
    FROM EMPLOYEES E JOIN DEPARTMENTS D 
    ON E.DEP_ID = D.DEPT_ID_DEP
    JOIN JOBS J ON E.JOB_ID = J.JOB_IDENT
    LEFT JOIN JOB_HISTORY JH ON E.EMP_ID = JH.EMPL_ID
    GROUP BY E.EMP_ID, E.F_NAME, E.L_NAME, E.SALARY, D.DEP_NAME, J.JOB_TITLE
)
SELECT * FROM CAREER_SUMMARY
ORDER BY SALARY_RANK;